-- DEPRECATED MIGRATION
-- Conversation optimizations folded into initial_migration.sql.
-- Retained as a no-op so schema_migrations entries can remain unchanged.
-- This file intentionally left blank.
