// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KellySuggestion = { kelly_suggestion: number, quarter_kelly: number, current_prob: number, balance: number, };
