// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MarketUpdate = { event_id: number, target_prob: number, stake: number, referral_post_id: number | null, referral_click_id: number | null, };
