// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MarketOutcomeView = { outcome_id: bigint, outcome_key: string, label: string, prob: number, q_value: number, lower_bound: number | null, upper_bound: number | null, };
