// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MarketEvent = { id: number, topic_id: number | null, title: string, details: string | null, closing_date: string | null, outcome: string | null, event_type: string | null, market_prob: number, liquidity_b: number, cumulative_stake: number, };
