// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MarketOutcomeView } from "./MarketOutcomeView";

export type OutcomeUpdateResult = { event_id: number, outcome_id: bigint, prev_prob: number, new_prob: number, shares_acquired: number, hold_until: string, market_prob: number, outcomes: Array<MarketOutcomeView>, market_outcome_update_id: bigint, };
