// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateResult = { prev_prob: number, new_prob: number, shares_acquired: number, share_type: string, hold_until: string, expected_payout_if_yes: number, expected_payout_if_no: number, market_update_id: number, };
