/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_mlsclient_free: (a: number, b: number) => void;
export const mlsclient_add_member: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const mlsclient_clear_groups: (a: number) => void;
export const mlsclient_create_group: (a: number, b: number, c: number) => [number, number, number, number];
export const mlsclient_create_identity: (a: number, b: number, c: number) => [number, number, number, number];
export const mlsclient_decrypt_message: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const mlsclient_derive_key_argon2id: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const mlsclient_drain_storage_events: (a: number) => [number, number, number];
export const mlsclient_encrypt_message: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const mlsclient_export_storage_state: (a: number) => [number, number, number, number];
export const mlsclient_get_credential_bytes: (a: number) => [number, number, number, number];
export const mlsclient_get_group_ids: (a: number) => any;
export const mlsclient_get_identity_fingerprint: (a: number) => [number, number, number, number];
export const mlsclient_get_key_package_bundle_bytes: (a: number) => [number, number, number, number];
export const mlsclient_get_key_package_bytes: (a: number) => [number, number, number, number];
export const mlsclient_get_sent_message: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const mlsclient_get_signature_keypair_bytes: (a: number) => [number, number, number, number];
export const mlsclient_has_group: (a: number, b: number, c: number) => number;
export const mlsclient_import_storage_state: (a: number, b: number, c: number) => [number, number];
export const mlsclient_new: () => number;
export const mlsclient_process_commit: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const mlsclient_process_welcome: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const mlsclient_regenerate_key_package: (a: number) => [number, number];
export const mlsclient_restore_identity: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const mlsclient_store_sent_message: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const init_logging: () => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
